# Form implementation generated from reading ui file '.\templates\About.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    def setupUi(self, dlgAbout):
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.resize(400, 300)
        dlgAbout.setMinimumSize(QtCore.QSize(400, 300))
        dlgAbout.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\templates\\../img/Logo1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgAbout.setWindowIcon(icon)
        self.btnCerrraAbout = QtWidgets.QPushButton(parent=dlgAbout)
        self.btnCerrraAbout.setGeometry(QtCore.QRect(160, 260, 75, 23))
        self.btnCerrraAbout.setObjectName("btnCerrraAbout")
        self.frame = QtWidgets.QFrame(parent=dlgAbout)
        self.frame.setGeometry(QtCore.QRect(10, 10, 371, 241))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(110, 10, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(110, 60, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(110, 100, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 151, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 91, 91))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(".\\templates\\../img/Logo1.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setGeometry(QtCore.QRect(20, 140, 81, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 170, 181, 61))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(".\\templates\\../img/by-nc-nd.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(dlgAbout)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "Dialog"))
        self.btnCerrraAbout.setText(_translate("dlgAbout", "Cerrar"))
        self.label.setText(_translate("dlgAbout", "Car Teis ®"))
        self.label_2.setText(_translate("dlgAbout", "Alquiler de Coches"))
        self.label_4.setText(_translate("dlgAbout", "06/10/2023 Pablo Sierra Pérez"))
        self.label_6.setText(_translate("dlgAbout", "IES de Teis"))
