# Form implementation generated from reading ui file '.\templates\Calendar.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_digCalendar(object):
    def setupUi(self, digCalendar):
        digCalendar.setObjectName("digCalendar")
        digCalendar.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        digCalendar.resize(400, 300)
        digCalendar.setMinimumSize(QtCore.QSize(400, 300))
        digCalendar.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\templates\\../img/Logo1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        digCalendar.setWindowIcon(icon)
        digCalendar.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(digCalendar)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.Calendar = QtWidgets.QCalendarWidget(parent=digCalendar)
        self.Calendar.setMinimumSize(QtCore.QSize(400, 300))
        self.Calendar.setMaximumSize(QtCore.QSize(400, 300))
        self.Calendar.setObjectName("Calendar")
        self.gridLayout.addWidget(self.Calendar, 0, 0, 1, 1)

        self.retranslateUi(digCalendar)
        QtCore.QMetaObject.connectSlotsByName(digCalendar)

    def retranslateUi(self, digCalendar):
        _translate = QtCore.QCoreApplication.translate
        digCalendar.setWindowTitle(_translate("digCalendar", "Dialog"))
