# Form implementation generated from reading ui file '.\templates\Salir.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgSalir(object):
    def setupUi(self, dlgSalir):
        dlgSalir.setObjectName("dlgSalir")
        dlgSalir.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dlgSalir.resize(400, 300)
        dlgSalir.setMinimumSize(QtCore.QSize(400, 300))
        dlgSalir.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\templates\\../img/Logo1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgSalir.setWindowIcon(icon)
        dlgSalir.setModal(True)
        self.lblSalir = QtWidgets.QLabel(parent=dlgSalir)
        self.lblSalir.setGeometry(QtCore.QRect(90, 70, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblSalir.setFont(font)
        self.lblSalir.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.lblSalir.setObjectName("lblSalir")
        self.btnSalirAceptar = QtWidgets.QPushButton(parent=dlgSalir)
        self.btnSalirAceptar.setGeometry(QtCore.QRect(80, 210, 75, 23))
        self.btnSalirAceptar.setObjectName("btnSalirAceptar")
        self.btnSalirCancelar = QtWidgets.QPushButton(parent=dlgSalir)
        self.btnSalirCancelar.setGeometry(QtCore.QRect(240, 210, 75, 23))
        self.btnSalirCancelar.setObjectName("btnSalirCancelar")

        self.retranslateUi(dlgSalir)
        QtCore.QMetaObject.connectSlotsByName(dlgSalir)

    def retranslateUi(self, dlgSalir):
        _translate = QtCore.QCoreApplication.translate
        dlgSalir.setWindowTitle(_translate("dlgSalir", "Dialog"))
        self.lblSalir.setText(_translate("dlgSalir", "¿Desea Usted Salir?"))
        self.btnSalirAceptar.setText(_translate("dlgSalir", "Aceptar"))
        self.btnSalirCancelar.setText(_translate("dlgSalir", "Cancelar"))
